	.align 2
gText_ConfirmSave::
	.string "Yea, you better save.$"

gText_AlreadySavedFile::
	.string "You already have one.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOff::
	.string "Saving that shit...\n"
	.string "Almost...$"

gText_PlayerSavedGame::
	.string "I got you {PLAYER}, all good.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "You fucked up.\p"
	.string "Bad.\n"
	.string "Replace backup memory.$"

gText_SavingDontTurnOffPower::
	.string "Saving that shit...\n"
	.string "Almost...$"
